rdb:
  nworkers: null
  constring: "dbname='mine2' user='pdbj' port=5433"

pipelines:
  # pdbj: CIF is default, -json suffix for mmJSON
  pdbj:
    data: /home/nagaet/pdb/data/structures/divided/mmCIF/
    data-plus: /home/nagaet/pdb/pdbj/pdbjplus/data/pdb/mmjson-plus/
  pdbj-json:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/pdb/mmjson-noatom/
    data-plus: /home/nagaet/pdb/pdbj/pdbjplus/data/pdb/mmjson-plus/
  # cc: CIF is default
  cc:
    data: /home/nagaet/pdb/data/monomers/
  cc-json:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/cc/mmjson/
  # prd: CIF is default
  prd:
    data: /home/nagaet/pdb/data/bird/prd/
  prd-json:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/prd/mmjson/
  # ccmodel: CIF is default
  ccmodel:
    data: /home/nagaet/pdb/data/component-models/complete/
  ccmodel-json:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/ccmodel/mmjson/
  # Other pipelines
  vrpt:
    data: /home/nagaet/pdb/validation_reports/
  contacts:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/pdb/contacts/
  sifts:
    data: /home/nagaet/pdb/pdbj/pdbjplus/data/sifts/rdf/
