rdb:
  nworkers: 4  # テスト用なので少なめ
  constring: "dbname='mine2_test' user='pdbj' port=5433"

obabel: /usr/bin/obabel
  
pipelines:
  pdb:
    deffile: ${CWD}schemas/pdbj.def.yml
    data: ${CWD}data/mmjson-noatom/
    data-plus: ${CWD}data/plus/
  cc:
    deffile: ${CWD}schemas/cc.def.yml
    data: ${CWD}data/cc/
  ccmodel:
    deffile: ${CWD}schemas/ccmodel.def.yml
    data: ${CWD}data/ccmodel/
  prd:
    deffile: ${CWD}schemas/prd.def.yml
    data: ${CWD}data/prd/
  vrpt:
    deffile: ${CWD}schemas/vrpt.def.yml
    data: ${CWD}/data/vrpt/*
    dic: ${CWD}dictionaries/mmcif_pdbx_vrpt.dic.gz
  emdb:
    deffile: ${CWD}schemas/emdb.def.yml
    data: ${CWD}data/emdb/
  ihm:
    deffile: ${CWD}schemas/ihm.def.yml
    data: ${CWD}data/ihm/
  contacts:
    deffile: ${CWD}schemas/contacts.def.yml
    data: ${CWD}data/contacts/
