rdb:
  nworkers: null
  constring: "dbname='mine2' user='pdbj' port=5433"

obabel: /usr/bin/obabel

pipelines:
  # pdbj: CIF is default, -json suffix for mmJSON
  pdbj:
    deffile: ${CWD}schemas/pdbj.def.yml
    data: /mnt/c/pdb/data/structures/divided/mmCIF/
    data-plus: /mnt/c/pdb/pdbj/pdbjplus/data/pdb/mmjson-plus/
  pdbj-json:
    deffile: ${CWD}schemas/pdbj.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/pdb/mmjson-noatom/
    data-plus: /mnt/c/pdb/pdbj/pdbjplus/data/pdb/mmjson-plus/
  # cc: CIF is default
  cc:
    deffile: ${CWD}schemas/cc.def.yml
    data: /mnt/c/pdb/data/monomers/
  cc-json:
    deffile: ${CWD}schemas/cc.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/cc/mmjson/
  # prd: CIF is default
  prd:
    deffile: ${CWD}schemas/prd.def.yml
    data: /mnt/c/pdb/data/bird/prd/
  prd-json:
    deffile: ${CWD}schemas/prd.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/prd/mmjson/
  # ccmodel: CIF is default
  ccmodel:
    deffile: ${CWD}schemas/ccmodel.def.yml
    data: /mnt/c/pdb/data/component-models/complete/
  ccmodel-json:
    deffile: ${CWD}schemas/ccmodel.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/ccmodel/mmjson/
  # Other pipelines
  vrpt:
    deffile: ${CWD}schemas/vrpt.def.yml
    data: /mnt/c/pdb/validation_reports/
  contacts:
    deffile: ${CWD}schemas/contacts.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/pdb/contacts/
  sifts:
    deffile: ${CWD}schemas/sifts.def.yml
    data: /mnt/c/pdb/pdbj/pdbjplus/data/sifts/rdf/
