rdb:
  nworkers: 12
  constring: "dbname='mine2' user='pdbj' password='pdbj_pwd' port=5432"
  
obabel: /usr/bin/obabel
  
pipelines:
  pdb:
    deffile: ${CWD}schemas/rdb.pdbj.def.yml
    data: ${CWD}data/plus-noatom/
  cc:
    deffile: ${CWD}schemas/rdb.cc.def.yml
    data: ${CWD}data/cc/
  ccmodel:
    deffile: ${CWD}schemas/rdb.ccmodel.def.yml
    data: ${CWD}data/ccmodel/
  prd:
    deffile: ${CWD}schemas/rdb.prd.def.yml
    data: ${CWD}data/prd/
  vrpt:
    deffile: ${CWD}schemas/rdb.vrpt.def.yml
    data: ${CWD}data/vrpt/
