[workspace]
authors = ["TomiiLabo <w255508b@yokohama-cu.ac.jp>"]
channels = ["conda-forge"]
name = "mine2updater"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
postgresql = ">=12.0.0,<13.0.0"
nodejs = ">=18.12.1,<18.13"
openbabel = ">=3.1.1,<4"

[activation.env]
PGPORT = "5433"
PGHOST = "localhost"
PGDATA = "postgres_data_5433"
PGUSER = "pdbj"
PGDATABASE = "mine2"
